# The name of the organisation or entity that owns this project
organisation: "Scott Semple"

# A live web address for the organisation
url: "https://www.scottsemple.com"

# The default contact email address
email: "scott@redlinealpine.com"

# The name of the project of books in this folder.
name: "Arrowhead Endurance"

# A one-liner about this project. Useful for Open Graph metadata.
description: "This is Arrowhead Endurance, a way to apply modern training methods to mountain sports. Created and maintained by Scott Semple."

# The logo of the organisation, saved web-ready in /assets
logo: "logo.svg"

# An image in /assets/images/web that stands for the project
image: "cover.jpg"

# Credit line, by default in the footer, overidden in locales.yml
credit: "Built with the [Electric Book](https://ebw.co/template)"

# Primary language code for this project as a whole
language: "en"

# App bundle ID unique across all app stores
app-id: com.example.myapp

# Version. You must change this with each app update
version: "0.0.1"
