name: Check build
on:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 2

            - name: Set up Ruby 2.7
              uses: actions/setup-ruby@v1
              with:
                ruby-version: 2.7

            - name: Install Bundler
              run: gem install bundler

            - name: Bundle install
              run: bundle install

            - name: Build with Jekyll
              run: |
                bundle exec jekyll build
